const blackDeck = [];

blackDeck.push("___.  Betcha can't have just one!");
blackDeck.push("___.  High five, bro.");
blackDeck.push("___.  It's a trap!");
blackDeck.push("___.  That's how I want to die.");
blackDeck.push("___: good to the last drop.");
blackDeck.push("___: kid tested, mother-approved.");
blackDeck.push("A romantic, candlelit dinner would be incomplete without ___.");
blackDeck.push("After the earthquake, Sean Penn brought ___ to the people of Haiti.");
blackDeck.push("Alternative medicine is now embracing the curative powers of ___.");
blackDeck.push("BILLY MAYS HERE FOR ___.");
blackDeck.push("But before I kill you, Mr. Bond, I must show you ___.");
blackDeck.push("Coming to Broadway this season, ___: The Musical.");
blackDeck.push("Daddy, why is mommy crying?");
blackDeck.push("Dear Abby, I'm having some trouble with ___ and would like your advice.");
blackDeck.push("During his childhood, Salvador Dalí produced hundreds of paintings of ___.");
blackDeck.push("During sex, I like to think about ___.");
blackDeck.push("Here is the church.  Here is the steeple.  Open the doors.  And there is ___.");
blackDeck.push("How am I maintaining my relationship status?");
blackDeck.push("How did I lose my virginity?");
blackDeck.push("I do not know with what weapons World War III will be fought, but World War IV will be fought with ___.");
blackDeck.push("I drink to forget ___.");
blackDeck.push("I got 99 problems but ___ ain't one.");
blackDeck.push("I'm sorry, Professor, but I couldn't complete my homework because of ___.");
blackDeck.push("In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?");
blackDeck.push("In L.A. County Jail, word is you can trade 200 cigarettes for ___.");
blackDeck.push("In Michael Jackson's final moments, he thought about ___.");
blackDeck.push("In the new Disney Channel Original Movie, Hannah Montana struggles with ___ for the first time.");
blackDeck.push("Instead of coal, Santa now gives the bad children ___.");
blackDeck.push("It's a pity that kids these days are all getting involved with ___.");
blackDeck.push("Life for American Indians was forever changed when the White Man introduced them to ___.");
blackDeck.push("Major League Baseball has banned ___ for giving players an unfair advantage.");
blackDeck.push("Maybe she's born with it.  Maybe it's ___.");
blackDeck.push("MTV's new reality show features eight washed-up celebrities living with ___.");
blackDeck.push("Next from J.K. Rowling: Harry Potter and the Chamber of ___.");
blackDeck.push("Next on ESPN2: The World Series of ___.");
blackDeck.push("Studies show that lab rats navigate mazes 50% faster after being exposed to ___.");
blackDeck.push("The class field trip was completely ruined by ___.");
blackDeck.push("The Smithsonian Museum of Natural History has just opened an interactive exhibit on ___.");
blackDeck.push("This is the way the world ends.  This is the way the world ends.  Not with a bang but with ___.");
blackDeck.push("TSA guidelines now prohibit ___ on airplanes.");
blackDeck.push("War!  What is it good for?");
blackDeck.push("What am I giving up for Lent?");
blackDeck.push("What are my parents hiding from me?");
blackDeck.push("What did I bring back from Mexico?");
blackDeck.push("What did the US airdrop to the children of Afghanistan?");
blackDeck.push("What did Vin Diesel eat for dinner?");
blackDeck.push("What do old people smell like?");
blackDeck.push("What does Dick Cheney prefer?");
blackDeck.push("What don't you want to find in your Kung Pao chicken?");
blackDeck.push("What ended my last relationship?");
blackDeck.push("What gets better with age?");
blackDeck.push("What gives me uncontrollable gas?");
blackDeck.push("What helps Obama unwind?");
blackDeck.push("What is Batman's guilty pleasure?");
blackDeck.push("What never fails to liven up the party?");
blackDeck.push("What will always get you laid?");
blackDeck.push("What will I bring back in time to convince people that I am a powerful wizard?");
blackDeck.push("What would Grandma find disturbing, yet oddly charming?");
blackDeck.push("What’s Teach for America using to inspire inner city students to succeed?");
blackDeck.push("What's a girl's best friend?");
blackDeck.push("What's my anti-drug?");
blackDeck.push("What's my secret power?");
blackDeck.push("What's that smell?");
blackDeck.push("What's that sound?");
blackDeck.push("What's the most emo?");
blackDeck.push("What's the new fad diet?");
blackDeck.push("What's the next Happy Meal® toy?");
blackDeck.push("What's the next superhero/sidekick duo?");
blackDeck.push("What's there a ton of in heaven?");
blackDeck.push("When I am a billionaire, I shall erect a 50-foot statue to commemorate ___.");
blackDeck.push("When I am President of the United States, I will create the Department of ___.");
blackDeck.push("When Pharaoh remained unmoved, Moses called down a Plague of ___.");
blackDeck.push("While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ___.");
blackDeck.push("White people like ___.");
blackDeck.push("Why am I sticky?");
blackDeck.push("Why can't I sleep at night?");
blackDeck.push("Why do I hurt all over?");

exports.getBlackDeck = function() {
	var n = blackDeck.length;
	for(var i = 0; i < n; i++) {
		// Fisher-Yates Randomization In Place
		var temp = blackDeck[i];
		var randomNumber = Math.floor((Math.random()* (n-1) +1));
		blackDeck[i] = blackDeck[randomNumber];
		blackDeck[randomNumber] = temp;
	}
    return blackDeck;
}